### ISSUE TITLE
  Uncaught exception 'Exception' with message 'Curl error: Cannot communicate securely with peer: no common encryption algorithm(s).'

### ISSUE THREAD

**Issue by jurasseck** [DeveloperCielo/Webservice-1.5-php#68]
Boa tarde,

Estou recebendo o seguinte erro quando tento realizar um pagamento utilizando a API.

```  Uncaught exception 'Exception' with message 'Curl error: Cannot communicate securely with peer: no common encryption algorithm(s).```

O trace que recebo é esse:

```
#Erro: 0 - Não foi possível executar este comando. Incorrect syntax near ','.
37
#Resultado: 

Fatal error:  Uncaught exception 'Exception' with message 'Curl error: Cannot communicate securely with peer: no common encryption algorithm(s).' in /var/www/html/webservicecielo/vendor/developercielo/webservice-1.5-php/src/Cielo/Http/CurlOnlyPostHttpClient.php:36
Stack trace:
#0 /var/www/html/webservicecielo/vendor/developercielo/webservice-1.5-php/src/Cielo/Cielo.php(175): Cielo\Http\CurlOnlyPostHttpClient->__invoke('https://ecommer...', Array, Array)
#1 /var/www/html/webservicecielo/vendor/developercielo/webservice-1.5-php/src/Cielo/Cielo.php(204): Cielo\Cielo->sendHttpRequest('<?xml version="...')
#2 /var/www/html/webservicecielo/doTransaction.php(74): Cielo\Cielo->transactionRequest(Object(Cielo\Transaction))
#3 {main}
  thrown in /var/www/html/webservicecielo/vendor/developercielo/webservice-1.5-php/src/Cielo/Http/CurlOnlyPostHttpClient.php on line 36

```

**Comment by tiagomarciano** [comment]
+1

**Comment by lucascolette** [comment]
O webservice da Cielo foi atualizado e só está suportando TLS 1.2

Precisa ser feito um ajuste na chamada Curl e atualizar a versão do SSL.

cc @netojoaobatista
